#delete from Credits where username="test_user";
#update OrdinaryAccounts set `Account number` = 'PL12122666666666666666666666' where username='user2';
select * from Users;
select * from UsersData;
select * from OrdinaryAccounts;
select * from SavingsAccounts;
select * from Credits;
select * from Cards;
select * from HistoryOrdinary;
select * from HistorySavings;
select h.* from HistoryOrdinary h join OrdinaryAccounts o on h.`Account nr from` = o.`Account number`where h.`Operation Date` >= '2022-06-05'and o.username='test_user';